version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: shteki_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sHADOW85@@&&
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    image: svdimov/shteki-web:latest  # Added for image tagging
    command: gunicorn Shteki.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:sHADOW85%40%40%26%26@db:5432/shteki_db  # URL-encoded password
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=adminpassword
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DEBUG=0
      - TZ=Europe/Sofia

volumes:
  pgdata:
  static_volume:
  media_volume: