  web:
    build: .
    command: gunicorn Shteki.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:sHADOW85@@&&@db:5432/shteki_db
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=adminpassword
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DEBUG=0
      - TZ=Europe/Sofia
