name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker-compose build
          docker tag your_project_web ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/your-app:latest
          docker push ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/your-app:latest

      - name: Azure WebApp Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: your-azure-app-name
          images: ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/your-app:latest
